INSERT INTO images (imageURL, imageType, imageDescription) VALUES
--Stephen
('https://i.imgur.com/jt0vy4o.jpg','AI','Bob'),
('https://i.imgur.com/yzU1l7d.jpg','AI','Bowl'),
('https://i.imgur.com/xUMGSdi.jpg','AI','Cat'),
('https://i.imgur.com/kLosgLf.jpg','AI','Dancing'),
('https://i.imgur.com/Fzup0Jw.jpg','AI','Homecoming'),
('https://i.imgur.com/ahMfCjg.jpg','AI','House'),
('https://i.imgur.com/rV5OjrH.jpg','AI','Jesus'),
('https://i.imgur.com/D4lqEKY.jpg','AI','Panda'),
('https://i.imgur.com/Ceyv64G.jpg','AI','School'),
('https://i.imgur.com/XpXUR4z.jpg','AI','Skull'),
('https://imgc.artprintimages.com/img/print/destination-signs-key-west-florida_u-l-pz52i30.jpg?artHeight=900&artPerspective=n&artWidth=900&background=fbfbfb','Real','Philippe Hugonnard'),
('https://www.boredpanda.com/blog/wp-content/uploads/2018/03/ugly-medieval-cats-art-103-5aafaff5c7b63__700.jpg','Real','Unknown'),
('https://pyxis.nymag.com/v1/imgs/bea/948/f6fcdc2fcbee41e96fdabd3be1cd0faf33-bonhams-cats-lot-68.rhorizontal.w807.jpg','Real','Henriette Ronner-Knip'),
('https://images.fineartamerica.com/images/artworkimages/mediumlarge/3/regal-renaissance-cat-portrait-painting-milly-may.jpg','Real','Milly May'),
('https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/colorful-crazy-lion-deep-dream-matthias-hauser.jpg','Real','Matthias Hauser'),
('https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/woman-with-dog-head-deep-dream-wild-and-crazy-matthias-hauser.jpg','Real','Matthias Hauser'),
('https://www.secondsandsurplus.com/media/amasty/webp/catalog/product/cache/3fe6aec9cc5f6c18d982cfde69d3b17f/a/r/artae2022_jpg.webp','Real','Seconds and Surplus'),
('https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/american-flag-flat-waving-v1-copy-6-roy-wylam.jpg','Real','Roy Wylam'),
('http://cdn.cnn.com/cnnnext/dam/assets/190516115302-h-r-giger-1.jpg','Real','H.R. Giger'),
('https://www.rct.uk/sites/default/files/styles/rctr-scale-1010w/public/256209-1330622370.jpg?itok=5HZ5Wwx_','Real','Portrait of a Man'),

--Nick
('https://i.imgur.com/JYmTZHB.jpg','AI','Abstract house on a rainy day'),
('https://i.imgur.com/lpPyJWD.jpg','AI','Black woman painting'),
('https://i.imgur.com/twRXIPS.jpg','AI','Drooping sunflower pot in a dimly lit room painting'),
('https://i.imgur.com/0X3QBhd.jpg','AI','Japanese style wave painting zoomed out paper texture'),
('https://i.imgur.com/P4cnhGs.jpg','AI','Award winning ai art'),
('https://i.imgur.com/TcvWEJc.jpg','AI','Award winning ai art'),
('https://i.imgur.com/4PkkbHW.jpg','AI','Gotten from thispersondoesnotexist.com'),
('https://i.imgur.com/MBAcE7p.jpg','AI','Castle clipart'),
('https://i.imgur.com/cwJJpjR.jpg','AI','A sun is born in an ethereal gas cloud nebula, painted by Alphonse Mucha and peter mohrbacher, with multiple matte black boarders on black paper background'),
('https://i.imgur.com/Sxwdqs5.jpg','AI','A coloring book page of a man desperately swimming'),
('https://i.imgur.com/rFBlGpp.jpg','Real','Study of a Young Woman - Johannes Vermeer'),
('https://i.imgur.com/hXcEQ5v.jpg','Real','Forest Man Painting - Ashley Parker Owens'),
('https://i.imgur.com/l813vnw.jpg','Real','Fantasy castle'),
('https://i.imgur.com/q6JEj7U.jpg','Real','El Greco - Self Portrait'),
('https://i.imgur.com/lc9DSNi.jpg','Real','The Jurist - Giuseppe Arcimboldo'),
('https://i.imgur.com/1rqnxTq.jpg','Real','neutral face person'),
('https://i.imgur.com/y3aUfZ8.jpg','Real','white chair picture'),
('https://i.imgur.com/LqDYpNN.jpg','Real','The New Light'),
('https://i.imgur.com/CCdo6np.jpg','Real','Modern Digital Art'),
('https://i.imgur.com/ZNWEcF9.jpg','Real','Blurry beach background'),

--Andrew
('https://imgur.com/wiYF654.jpg','AI','Lighthouse'),
('https://imgur.com/RZ2wXLM.jpg','AI','Vineyard'),
('https://imgur.com/n5tewlW.jpg','AI','Still Life'),
('https://imgur.com/QBu3UI9.jpg','AI','Rose Garden'),
('https://imgur.com/4RDRF9M.jpg','AI','Shipwreck'),
('https://i.imgur.com/Zel1G1F.jpg','AI','Beach'),
('https://i.imgur.com/0aWNwsi.jpg','AI','Midnight Train'),
('https://imgur.com/gEBoH24.jpg','AI','Lone Dog'),
('https://i.imgur.com/gNF2GIH.jpg','AI','Desert Night'),
('https://i.imgur.com/5DHMplh.jpg','AI','Cold Riverside'),
('https://i.imgur.com/fKajOE2.jpg','Real','My Cup Runneth Over, Stanley Rayfield'),
('https://i.imgur.com/nVd0bqM.jpg','Real','Insight, Raphaella Spence'),
('https://i.imgur.com/vSrQWrX.jpg','Real','Bus shelter 1, Dan Witz'),
('https://i.imgur.com/Vh2cnWt.jpg','Real','Still life with water glass, Ralph Goings'),
('https://i.imgur.com/5RkuObO.jpg','Real','Fortress, Jeremy Geddes'),
('https://i.imgur.com/cLvfwdP.jpg','Real','Yellow Iris, Erin Hanson'),
('https://i.imgur.com/499nwhz.jpg','Real','Winter, Ivan Shishkin'),
('https://i.imgur.com/sGksSJn.jpg','Real','The Regatta, Theo van Rysselberghe'),
('https://i.imgur.com/NeKgRa8.jpg','Real','A shorthorn cow, Henry Stafford'),
('https://i.imgur.com/EzIlI9c.jpg','Real','Whistlejacket, George Stubbs'),

--Zach
('https://i.imgur.com/1rwRORm.jpeg','AI','Panda in Pool'),
('https://i.imgur.com/603q9WK.jpeg','AI','Sunrise with Mountains'),
('https://i.imgur.com/dEvQ5XS.jpeg','AI','Bon Voyage'),
('https://i.imgur.com/xBy53Uv.jpeg','AI','Camera'),
('https://i.imgur.com/CJyiod6.jpeg','AI','Rosa Parks'),
('https://i.imgur.com/iQrHkmv.png','AI','Apple'),
('https://i.imgur.com/bXWAsPa.jpeg','AI','Pink Flower'),
('https://i.imgur.com/BYdS1Cm.jpeg','AI','Tree Person'),
('https://i.imgur.com/5BcjmWR.jpeg','AI','Red Hallway'),
('https://i.imgur.com/5BcjmWR.jpeg','AI','Future Workshop'),
('https://i.guim.co.uk/img/media/7d87784527d1145a1625eadf1c5105130af45c2a/0_119_2956_1774/master/2956.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=3cb09164aa8d4d5b280acdd230705ae7','Real','Elephant'),
('https://i.ytimg.com/vi/vdB-8eLEW8g/hqdefault.jpg','Real','Bob Marley'),
('https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/baby-raccoon-nikolay-radkov.jpg','Real','Raccoon'),
('https://www.nasa.gov/sites/default/files/styles/full_width/public/thumbnails/image/main_image_star-forming_region_carina_nircam_final-1280.jpg','Real','Space'),
('https://cdn1.epicgames.com/ue/product/Screenshot/000Main-1920x1080-842ea52baa1005898da286944574bc34.jpg?resize=1&w=1920','Real','Fantasy Planet'),
('https://assets-prd.ignimgs.com/2022/07/11/yetanotherfantasytitle-blogroll-1657574686231.jpg','Real','Fantasy'),
('https://iiif.micr.io/TZCqF/full/1280,/0/default.jpg','Real','Sunflowers'),
('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTb4U-QMvU1Gd7YC1S3nC9l8HDAVG9v2q3BQ&usqp=CAU','Real','Skull'),
('https://dreamsinparis.com/wp-content/uploads/2022/05/Impression-Sunrise-by-Claude-Monet2-1024x786.jpg','Real','Claude Monet'),
('https://sep.yimg.com/ty/cdn/madisonartshop/most-famous-paintings-20.jpg?t=1660737943&','Real','Dogs Playing Poker'),

--Ian Stewart
('https://images.nightcafe.studio/jobs/DotKrjOyVQLLemHGtDcB/DotKrjOyVQLLemHGtDcB--4--2zgue.jpg?tr=w-1600,c-at_max','AI','dark souls'),
('https://images.nightcafe.studio/jobs/DotKrjOyVQLLemHGtDcB/DotKrjOyVQLLemHGtDcB--1--4uyfc.jpg?tr=w-1600,c-at_max','AI','dark souls'),
('https://images.nightcafe.studio/jobs/DotKrjOyVQLLemHGtDcB/DotKrjOyVQLLemHGtDcB--2--14gdj.jpg?tr=w-1600,c-at_max','AI','dark souls'),
('https://images.nightcafe.studio/jobs/XNWxYAHBJAild2p3eZDY/XNWxYAHBJAild2p3eZDY--3--tbqh2.jpg?tr=w-1600,c-at_max','AI','end of the world'),
('https://images.nightcafe.studio/jobs/XNWxYAHBJAild2p3eZDY/XNWxYAHBJAild2p3eZDY--2--xhjpk.jpg?tr=w-1600,c-at_max','AI','end of the world'),
('https://images.nightcafe.studio/jobs/AeUBLZQyMDDlO7yNGFol/AeUBLZQyMDDlO7yNGFol--2--26jxz.jpg?tr=w-1600,c-at_max','AI','yhorm the giant'),
('https://images.nightcafe.studio/jobs/71JunKppzV3w3n3KC7ay/71JunKppzV3w3n3KC7ay.jpg?tr=w-1600,c-at_max','AI','gates to hell'),
('https://images.nightcafe.studio/jobs/q8oeVT5MgTJw6uKgnydo/q8oeVT5MgTJw6uKgnydo--4--0tniu.jpg?tr=w-1600,c-at_max','AI','sunset over the mountain range'),
('https://images.nightcafe.studio/jobs/q8oeVT5MgTJw6uKgnydo/q8oeVT5MgTJw6uKgnydo--3--be15v.jpg?tr=w-1600,c-at_max','AI','sunset over the mountain range'),
('https://images.nightcafe.studio/jobs/jn2JLN4rTdg2RQ6p51vX/jn2JLN4rTdg2RQ6p51vX--1--zxdif.jpg?tr=w-1600,c-at_max','AI','jungle canopy'),
('https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/bloodborne-art-oleksandr-vaznichenko.jpg','Real','Oleksandr Vaznichenko'),
('https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/9a8c87dc-a37a-4194-b8a6-c27e807996c6/dcvb5yv-9e82d010-6218-4866-8250-635d072d254d.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzlhOGM4N2RjLWEzN2EtNDE5NC1iOGE2LWMyN2U4MDc5OTZjNlwvZGN2YjV5di05ZTgyZDAxMC02MjE4LTQ4NjYtODI1MC02MzVkMDcyZDI1NGQuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.tg6wFR6l4GplQkEHzjQImuqtDr9YmT5C1kC06blUeDA','Real','BarsonYouTube'),
('https://res.cloudinary.com/cook-becker/image/fetch/q_auto,f_auto,w_1920,e_sharpen/https://candb.com/site/candb/images/artwork/kiln-of-the-first-flame-dark-souls-3-from-software.jpg','Real','Cook and becker'),
('https://images.fineartamerica.com/images/artworkimages/mediumlarge/3/dark-souls-3-juan-harris.jpg','Real','Juan Harris'),
('https://cdnb.artstation.com/p/assets/images/images/000/523/489/large/brandon-fernandes-ds2.jpg?1425562147 ','Real','Brandon Fernandes'),
('https://ih1.redbubble.net/image.2891604595.1720/flat,750x,075,f-pad,750x1000,f8f8f8.jpg','Real','Ali Shimhaq'),
('https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/24e28a28-6fcb-4981-8385-c8c666433680/d464vj0-9d566f0c-21f5-4bd6-aac2-8c844fe2fb4d.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzI0ZTI4YTI4LTZmY2ItNDk4MS04Mzg1LWM4YzY2NjQzMzY4MFwvZDQ2NHZqMC05ZDU2NmYwYy0yMWY1LTRiZDYtYWFjMi04Yzg0NGZlMmZiNGQuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.mJIUNFHchoZ_ORJeXbl6QCjy1Rcj-b0fmlcyaAkmawc','Real','renata-studio'),
('https://img.artpal.com/96513/5-15-3-8-15-42-4m.jpg','Real','Steve Armstrong'),
('https://www.simplemost.com/wp-content/uploads/2021/12/AdobeStock_125898822.jpeg','Real','vovik_mar'),
('https://i.pinimg.com/originals/70/83/e0/7083e058abafbaa41e0284f8cfa4fbc7.jpg','Real','Charles Hartley'),

--Ian Von Pechmann
('https://i.imgur.com/wv2417y.png','AI','The sun rising behind a magnificent lion'),
('https://i.imgur.com/lWj9S7x.png','AI','Pandas scolding you for being a failure'),
('https://i.imgur.com/IhrjkCx.png','AI','A thief arguing with a mime'),
('https://i.imgur.com/5MiLbos.jpg','AI','The Kraken in the dark'),
('https://i.imgur.com/GPZoraH.jpg','AI','Sad clown'),
('https://i.imgur.com/LBDH43N.jpg','AI','Purple leopard in a busy city'),
('https://i.imgur.com/tgMdyMN.jpg','AI','Old Asian woman'),
('https://i.imgur.com/bpmWbu8.jpg','AI','Broken down car by a sad dog'),
('https://i.imgur.com/X6Q1wgV.jpg','AI','Blue jungle'),
('https://i.imgur.com/nesXgXr.jpg','AI','A gentle turtle giving thanks'),
('https://render.fineartamerica.com/images/rendered/default/print/6.5/8/break/images/artworkimages/medium/1/african-lion-lucie-bilodeau.jpg','Real','Lucie Bilodeau'),
('https://www.novica.com/blog/wp-content/uploads/2016/09/lordofjungle.jpg','Real','Andres A. Carreto'),
('https://www.parkwestgallery.com/wp-content/uploads/2018/09/884156-lets-make-a-wish_ilyayev-jpg.jpg','Real','S. Ilyayev'),
('https://i.etsystatic.com/5150206/r/il/1dd83b/1785974556/il_fullxfull.1785974556_696x.jpg','Real','Aja'),
('https://www.this-is-cool.co.uk/wp-content/gallery/koveck-art/the-art-of-koveck-11.jpg','Real','Koveck'),
('https://images.fineartamerica.com/images-medium-large-5/dark-sea-demoncio.jpg','Real','Demoncio'),
('https://images.fineartamerica.com/images/artworkimages/mediumlarge/3/the-post-apocalyptic-world-realiten-digital-art.jpg','Real','Realiten'),
('https://c4.wallpaperflare.com/wallpaper/924/878/435/sta%C5%84czyk-digital-art-joker-wallpaper-thumb.jpg','Real','Jan Matejko'),
('https://images.saatchiart.com/saatchi/696454/art/6518701/5588377-HSC00002-7.jpg','Real','Janaka Stagnaro'),
('https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/surreal-tiger-bubble-water-dancer-daniel-eskridge.jpg','Real','Daniel Eskridge');

--User dummy data
INSERT INTO users (username, password, highscore, totalImages) VALUES
('John', '$2b$10$uQcdAj60G6QCtLO3nha1Ae9C05p5tW0sT3lYv0gufgc9UIS96lp/G', 100, 500),
('Jill', '$2b$10$uQcdAj60G6QCtLO3nha1Ae9C05p5tW0sT3lYv0gufgc9UIS96lp/G', 10, 11),
('Jack', '$2b$10$uQcdAj60G6QCtLO3nha1Ae9C05p5tW0sT3lYv0gufgc9UIS96lp/G', 2, 3),
('Bob', '$2b$10$uQcdAj60G6QCtLO3nha1Ae9C05p5tW0sT3lYv0gufgc9UIS96lp/G', 24, 25),
('Alex', '$2b$10$uQcdAj60G6QCtLO3nha1Ae9C05p5tW0sT3lYv0gufgc9UIS96lp/G', 67, 68),
('Jaclyn', '$2b$10$uQcdAj60G6QCtLO3nha1Ae9C05p5tW0sT3lYv0gufgc9UIS96lp/G', 7, 8),
('Maya', '$2b$10$uQcdAj60G6QCtLO3nha1Ae9C05p5tW0sT3lYv0gufgc9UIS96lp/G', 7, 8),
('Julio', '$2b$10$uQcdAj60G6QCtLO3nha1Ae9C05p5tW0sT3lYv0gufgc9UIS96lp/G', 12, 13),
('Juan', '$2b$10$uQcdAj60G6QCtLO3nha1Ae9C05p5tW0sT3lYv0gufgc9UIS96lp/G', 5, 6),
('Luke', '$2b$10$uQcdAj60G6QCtLO3nha1Ae9C05p5tW0sT3lYv0gufgc9UIS96lp/G', 34, 35),
('admin','$2b$10$3xKb9LOGJeWC46.Adbkhseak1IZoBrGrWyW/QOwgQ0njb1dtYWcs.',0,0);